services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql
  wp:
    image: wordpress:php8.1-apache
    depends_on: [db]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    ports: ["8080:80"]
    volumes:
      - ./data/wp:/var/www/html
